import('./js/header.js');
import('./js/mobile-menu.js');
import('./js/hero.js');
import('./js/quotes.js');
import('./js/exercises.js');
import('./js/exercises-details.js');
import('./js/footer.js');
import('./js/favorites.js');
import('./js/modal-menu.js');
